apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-project-cloud-platform
  namespace: platform-system
  labels:
    platform.myorg.io/type: gcp-project
    platform.myorg.io/team: alpha
data:
  projectId: "cloud-platform-2f1d"
  projectNumber: "151303392630"
  environment: "dev"
  team: "alpha"
