apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-platform
  description: "GCP Project backstage-platform-f417 for team platform (prod)"
  annotations:
    google.com/project-id: "backstage-platform-f417"
    google.com/project-number: "696497703005"
  tags:
    - gcp
    - platform
    - prod
  links:
    - url: "https://console.cloud.google.com/home/dashboard?project=backstage-platform-f417"
      title: "GCP Console"
      icon: cloud
spec:
  type: gcp-project
  owner: group:platform
  lifecycle: production
