apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-project-platform-project
  namespace: platform-system
  labels:
    platform.myorg.io/type: gcp-project
    platform.myorg.io/team: alpha
data:
  projectId: "platform-project-7070"
  projectNumber: "864340854265"
  environment: "dev"
  team: "alpha"
